import Link from 'next/link';

export const metadata = {
  title: 'About Next App',
  description: 'Generated by Surafel',
};

const layout = ({ children }: { children: React.ReactNode }) => {
  return (
    <>
      <Link href={'/'}>To Home Page</Link>
      {children}
    </>
  );
};

export default layout;
